### ISSUE TITLE
Dimensions::fitWidthandHeight wrong upscale when $force=true

### ISSUE THREAD

**Issue by distantnative** [k-next/toolkit#14]
```php
    public function testResize()
    {
        $dimensions = new Dimensions(1200, 768);
        $dimensions->resize(2000, 800, true);
        $this->assertEquals(1250, $dimensions->width());
        $this->assertEquals(800, $dimensions->height());
    }
```

This test currently passes. But I would assume that when I force an upscale to 2000x800, it will end with the 2000 width.

**Comment by bastianallgeier** [comment]
I actually think this is correct. Because fitWidthAndHeight tries to keep within the boundaries of both values. So it cannot upscale the width further without exceeding the height.

**Comment by distantnative** [comment]
Ha, on point – maybe it's to early :joy:
