### ISSUE TITLE
Toolkit: v2 → v3

### ISSUE THREAD

**Issue by distantnative** [k-next/toolkit#17]
## Implemented/work in progress as Toolkit class
Class in v2 | Status for v3
-|-
**[A](https://github.com/getkirby/toolkit/tree/master/lib/a.php)** | implemented 
**[Collection](https://github.com/getkirby/toolkit/tree/master/lib/collection.php)** | work in progress: [PR](https://github.com/k-next/toolkit/pull/6) 
**[Dimensions](https://github.com/getkirby/toolkit/tree/master/lib/dimensions.php)** | work in progress: [PR](https://github.com/k-next/toolkit/pull/15) 
**[Obj](https://github.com/getkirby/toolkit/tree/master/lib/obj.php)** |  implemented
**[Pagination](https://github.com/getkirby/toolkit/tree/master/lib/pagination.php)** |  implemented
**[Server](https://github.com/getkirby/toolkit/tree/master/lib/server.php)** | implemented 
**[Str](https://github.com/getkirby/toolkit/tree/master/lib/str.php)** | implemented (maybe not all methods though) 
**[Url](https://github.com/getkirby/toolkit/tree/master/lib/url.php)** | implemented 
**[V](https://github.com/getkirby/toolkit/tree/master/lib/v.php)** | work in progress: [PR](https://github.com/k-next/toolkit/pull/12) 

## Implemented/work in progress as own package
Class in v2 | Status for v3
-|-
**[Brick](https://github.com/getkirby/toolkit/tree/master/lib/brick.php)** |  Element class in [Html package](https://github.com/k-next/html)
**[Data](https://github.com/getkirby/toolkit/tree/master/lib/data.php)** |  [Data package](https://github.com/k-next/data)
**[Database](https://github.com/getkirby/toolkit/tree/master/lib/database.php)** (incl. Query, maybe also DB) | [Database package](https://github.com/k-next/database) 
**[Dir](https://github.com/getkirby/toolkit/tree/master/lib/dir.php)** |  add to [FileSystem package](https://github.com/k-next/filesystem)
**[Embed](https://github.com/getkirby/toolkit/tree/master/lib/embed.php)** | [ Embed package](https://github.com/k-next/embed)
**[F](https://github.com/getkirby/toolkit/tree/master/lib/f.php)** |  add to [FileSystem package](https://github.com/k-next/filesystem)
**[Folder](https://github.com/getkirby/toolkit/tree/master/lib/folder.php)** |  add to [FileSystem package](https://github.com/k-next/filesystem)
**[Header](https://github.com/getkirby/toolkit/tree/master/lib/header.php)** |  add to [Http package](https://github.com/k-next/http)
**[Html](https://github.com/getkirby/toolkit/tree/master/lib/html.php)** |  [Html package](https://github.com/k-next/html)
**[R](https://github.com/getkirby/toolkit/tree/master/lib/r.php)** |  [Http package](https://github.com/k-next/http)
**[Redirect](https://github.com/getkirby/toolkit/tree/master/lib/redirect.php)** |  [Http package](https://github.com/k-next/http)
**[Remote](https://github.com/getkirby/toolkit/tree/master/lib/remote.php)** |  add to [Http package](https://github.com/k-next/http)
**[Response](https://github.com/getkirby/toolkit/tree/master/lib/response.php)** |  [Http package](https://github.com/k-next/http)
**[Router](https://github.com/getkirby/toolkit/tree/master/lib/router.php)** |  [Router package](https://github.com/k-next/router)
**[Sql](https://github.com/getkirby/toolkit/tree/master/lib/sql.php)** |  part of [Database package](https://github.com/k-next/database) 
**[Tpl](https://github.com/getkirby/toolkit/tree/master/lib/tpl.php)** |  [View package](https://github.com/k-next/view)
**[Upload](https://github.com/getkirby/toolkit/tree/master/lib/upload.php)** |  add to [FileSystem package](https://github.com/k-next/filesystem)?
**[Visitor](https://github.com/getkirby/toolkit/tree/master/lib/visitor.php)** |  add to [Http package](https://github.com/k-next/http)
**[YAML](https://github.com/getkirby/toolkit/tree/master/lib/yaml.php)** |  Yaml class in [Data package](https://github.com/k-next/data)

## Likely own packages
Class in v2 | Status for v3
-|-
**[Cache](https://github.com/getkirby/toolkit/tree/master/lib/cache.php)** (incl. drivers etc.) |  own package
**[Cookie](https://github.com/getkirby/toolkit/tree/master/lib/cookie.php)** |  own package (including Session as well)
**[Email](https://github.com/getkirby/toolkit/tree/master/lib/email.php)** |  own package
**[Exif](https://github.com/getkirby/toolkit/tree/master/lib/exif.php)** |  own package
**[Media](https://github.com/getkirby/toolkit/tree/master/lib/media.php)** |  add to Thumbs package
**[S](https://github.com/getkirby/toolkit/tree/master/lib/s.php)** |  own package (including Cookie as well)
**[Thumb](https://github.com/getkirby/toolkit/tree/master/lib/thumb.php)** |  own package

## Up for discussion
Class in v2 | Status for v3
-|-
**[Bitmask](https://github.com/getkirby/toolkit/tree/master/lib/bitmask.php)** | _not needed?_ 
**[C](https://github.com/getkirby/toolkit/tree/master/lib/c.php)** |  
**[Crypt](https://github.com/getkirby/toolkit/tree/master/lib/crypt.php)** |  _if needed, bundle in own package with Password_
**[Detect](https://github.com/getkirby/toolkit/tree/master/lib/detect.php)** |  _maybe own package together with System (e.g. called Environment)_
**[Error](https://github.com/getkirby/toolkit/tree/master/lib/error.php)** |  _could be Error package with Errorreporting?_
**[Errorreporting](https://github.com/getkirby/toolkit/tree/master/lib/errorreporting.php)** |  _could be Error package with Error?_
**[Escape](https://github.com/getkirby/toolkit/tree/master/lib/escape.php)** |  _not needed?_
**[I](https://github.com/getkirby/toolkit/tree/master/lib/i.php)** |  _not needed_
**[L](https://github.com/getkirby/toolkit/tree/master/lib/l.php)** |  _own Language package needed anyway?_
**[Password](https://github.com/getkirby/toolkit/tree/master/lib/password.php)** |   _if needed, bundle in own package with Crypt_
**[Silo](https://github.com/getkirby/toolkit/tree/master/lib/silo.php)** |  _depends on what we do with C and L_
**[System](https://github.com/getkirby/toolkit/tree/master/lib/system.php)** |    _maybe own package together with System (e.g. called Environment)_
**[Timer](https://github.com/getkirby/toolkit/tree/master/lib/timer.php)** |  _not needed?_ 
**[Xml](https://github.com/getkirby/toolkit/tree/master/lib/xml.php)** |  _add to Data package or drop_

Let me hear your take on this, @bastianallgeier

**Comment by bastianallgeier** [comment]
@distantnative this is fantastic!! I will check it out more closely after the weekend. 👍

**Comment by bastianallgeier** [comment]
I moved this to Airtable to make it a bit more easy for us to edit and work with it: https://airtable.com/shrUKGKcShmFXWOm8/tbljstAowNOe58EAB

**Comment by distantnative** [comment]
I'm closing this here since we are woking on it on Airtable now. From the results on Airtable, we can then create individual, more approachable Issues in the respective packages.
